### ISSUE TITLE
CP4I Quick Start fails to deploy with default parameters

### ISSUE THREAD

**Issue by matrober-uk** [aws-quickstart/quickstart-ibm-integration#11]
A colleague and I have both tried the CP4I Quick Start today and observed that it fails very quickly with `S3 error: The specified key does not exist` on the "VPCStack" component as shown below.

<img width="1032" alt="Screenshot 2020-11-13 at 09 43 50" src="https://user-images.githubusercontent.com/32040584/99097617-c516dd00-25cf-11eb-92ca-47c15871ab91.png">

I've debugged this to the "Quick Start S3 key prefix" field, which currently has a default value of `quickstart-ibm-icp-for-integration/`, but that is not the correct name of the central S3 bucket in which the quick start templates are kept.

I've tested that the template works correctly when we update the "Quick Start S3 key prefix" to `quickstart-ibm-integration/`, which I will submit in the attached PR.

**A couple of unrelated bonus fixes**
In the attached PR I've also proposed text description changes to address a couple of points that I found confusing when going through from scratch;
- The user name to log in to the Platform Navigator is not entirely obvious so I've made it clearer by putting quotes around the "admin" part (and confirmed that is the correct user name)
- The description of the RH pull secret uses a Portworx file name example; I've updated to match the name of the file that is actually provided by Red Hat

**Comment by matrober-uk** [comment]
Preparing a PR to fix these items.

**Comment by vsnyc** [comment]
Good catch @matrober-uk - we specify the correct values in the tests so it got overlooked: 
https://github.com/aws-quickstart/quickstart-ibm-integration/blob/f7af573b6ae5f7e60f968dcd35b1fe0c64e60637/.taskcat.yml#L30-L32

**Comment by vsnyc** [comment]
Addressed in #12

**Comment by matrober-uk** [comment]
Confirmed the new default shows up as expected in the form template   👍 

<img width="975" alt="Screenshot 2020-11-13 at 18 12 32" src="https://user-images.githubusercontent.com/32040584/99106250-dbc33100-25db-11eb-982b-ea4465772d92.png">
